name: address_gen
description: Address and private/public key generator for PrivaCent
version: 0.0.2-dev
homepage: Wallet address and private/public key generator for Privacent
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  pointycastle: ^0.10.0+5
  base58check: ^0.1.1

dev_dependencies:
  test: ^0.12.0
